### ISSUE TITLE
MS login broken on staging

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1221]
**Describe the bug**
![image](https://github.com/memphis-iis/mofacts-ies/assets/13023147/add6826e-0b59-4435-bb62-f28462abda0a)

**Comment by JRustyHaner** [comment]
@imrryr We need to register you a free microsoft azure saml account. This will give us the clientId and secret to configure mofacts with.

**Comment by imrryr** [comment]
Yay, I needed to finish the signup process. I don't think it completed when we were meeting, or perhaps it didn't work for the Memphis.edu account. Anyhow, I have confirmed a clean account can be signed up. What's next

**Comment by JRustyHaner** [comment]
@imrryr 

https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app  

use the option that allows for Accounts in any organizational directory.  The web redirect should be the same as it was in google

**Comment by imrryr** [comment]
OK, not working, lets talk about it Monday

**Comment by JRustyHaner** [comment]
@imrryr the Redirect URLs I gave you are wrong. I sent you an email recently with the correct ones. 

https://staging.optimallearning.org/_oauth/office365
https://mofacts.optimallearning.org/_oauth/office365

**Comment by imrryr** [comment]
I did this, not sure if it is working...

**Comment by imrryr** [comment]
![C__Users_ppavl_Dropbox_Active projects_mofacts_config2_IndividualOptim_OptimTester1 preflight json - Notepad++ 10_31_2023 5_06_35 PM](https://github.com/memphis-iis/mofacts-ies/assets/13023147/7ecaff84-ed16-4685-940b-cd8f7d33428b)

**Comment by JRustyHaner** [comment]
I'll check the server logs. That's a good step though.

**Comment by JRustyHaner** [comment]
@imrryr  the error: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app

**Comment by imrryr** [comment]
@JRustyHaner does that mean you can fix it?

**Comment by imrryr** [comment]
It is still stuck when I try this. I select my account and then this error occurs...
![mofacts_app - Google Chrome 11_16_2023 8_43_39 AM](https://github.com/memphis-iis/mofacts-ies/assets/13023147/888980c9-2677-4309-bd25-73538168afd2)

**Comment by JRustyHaner** [comment]
@imrryr  for reference:

Sessions.json:

    "microsoft":{
        "clientId": "<Application (client) ID>",
        "secret":" "<Value>"
    },

These settings allowed for a MS login
