### ISSUE TITLE
mofacts full server

### ISSUE THREAD

**Issue by JRustyHaner** [memphis-iis/mofacts#1303]
http://iisml-precision-7920-tower.uom.memphis.edu/

**Comment by imrryr** [comment]
I can't seem to connect here. @JRustyHaner Should it work off campus?

**Comment by JRustyHaner** [comment]
No, you have to use the vpn

**Comment by imrryr** [comment]
@JRustyHaner content creation is not working. Please test it for the new version before completing this issue. My test does not produce an email.
