### ISSUE TITLE
Ubiquitous downloading just a bit confusing

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1320]
in the content upload tool, it appears we are tracking all packages ever uploaded in the second menu, but the first menu shows the valid packages, and also includes a json link......

I'm wondering if this could be simplified to remove the package download second second, and make the json download button in the first menu just give the original package entirely like the second menu allows.

Further, the minus "-" button could remove both the package from the server entirely (rather than keep it is some folder as it appears we are doing now). Also the minus button should include a warning dialog about being unrecoverable or something.

**Comment by JRustyHaner** [comment]
@imrryr that will work, but when we change it, it will only effect new uploads, since the database is not keeping track of which zip belongs to which tdf.
