### ISSUE TITLE
Memphis SSO passthrough support

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1324]
According to ChatGPT we need to do these things when setting up for Canvas. Please estimate how long this might take under different scenarios of with or without grade passback

**Comment by imrryr** [comment]
Converting a JavaScript app into an LTI (Learning Tools Interoperability) plugin for Canvas involves several steps. LTI is a standard developed by IMS Global that allows integration of learning applications with platforms like Canvas. Here's a general outline of the process:

1. **Understand LTI Specifications**: Familiarize yourself with the LTI standard. LTI 1.3 is the latest version and it's quite different from the previous versions. It uses OAuth 2.0 for security, so you'll need to understand how this works.

2. **Set Up a Development Environment**: Ensure you have a suitable environment for developing and testing your LTI tool. This might include setting up a local development server and getting access to a Canvas instance (you can use a free Canvas account for testing).

3. **Modify Your App to Support LTI**: 
   - **Authentication**: Implement OAuth 2.0 for authentication. Canvas will send an LTI launch request to your tool, which includes a JWT (JSON Web Token) for security.
   - **Data Handling**: Your app will need to handle LTI launch requests and extract necessary data from them, like user information, course details, etc.
   - **Deep Linking (if needed)**: If your tool needs to support content-item selection or deep linking, implement LTI Deep Linking 2.0.

4. **Register Your Tool with Canvas**:
   - In your Canvas instance, you'll need to register your tool as an external app. This involves providing details like the launch URL, key, and secret.
   - For LTI 1.3, you'll also need to set up a platform registration with your tool, which involves exchanging URLs, keys, and other details for secure communication.

5. **Testing and Debugging**:
   - Test your tool extensively within the Canvas environment. Ensure that it handles authentication, data exchange, and any specific interactions (like grade pass-back or content selection) correctly.
   - Debug any issues that arise and ensure compliance with LTI standards.

6. **Documentation and Support**:
   - Prepare documentation for your tool that explains how to install and use it in Canvas.
   - Set up support channels for users of your tool.

7. **Publish and Maintain**:
   - Once tested, you can publish your tool for others to use.
   - Regularly update the tool to maintain compatibility with Canvas updates and LTI specifications.

8. **Stay Informed**:
   - Keep yourself updated with the LTI standards and Canvas API updates to ensure your tool remains compatible and secure.

Since this is a technical process involving multiple standards and technologies, it would be beneficial to have a good understanding of JavaScript, server-side programming (for handling OAuth and launch requests), and the specific requirements of the Canvas LTI API. You might also want to look into existing libraries or frameworks that can help with LTI integration.

**Comment by imrryr** [comment]
https://www.imsglobal.org/spec/lti/v1p3

**Comment by JRustyHaner** [comment]
@imrryr  https://forums.meteor.com/t/is-lti-integration-possible-for-meteor-applications/49420

Not as complicated as we think. The Accounts package that we already use can handle oAuth from a LMS using Accounts.registerLoginHandler. There is a node package for handling the POST response from the LMS (ims-lti). After that information is received, they are logged in to meteor to the profile page.

**Comment by imrryr** [comment]
Lets do this taks as time allows.

**Comment by imrryr** [comment]
I discovered I should do both the faculty and vendor forms online. I will do so as time allows.
