### ISSUE TITLE
Loading issue for the bird experiment and the crash of the mongo server

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts#1327]
I was running the bird experiment at https://mofacts.optimallearning.org/experiment/birdcategory   
The system crashed and showed loading on the webpage. 
I'm running with a batch size of 9. But usually there were fewer participants working on it simultaneously.

**Comment by imrryr** [comment]
So Rusty suggested it was a load issue. Can we diagnose what is causing it ASAP? Is it likely to be related to the images (i.e. are they in Mongo?)? Would image hosting then fix the issue? @MegaGeese @JRustyHaner

**Comment by imrryr** [comment]
As I described in my email, the database use on the server should be low, since it isn't needed except to start up and receive a little data from each trial...

**Comment by JRustyHaner** [comment]
@imrryr this was a mongo cache configuration error. I've corrected it to where it is highly unlikely to occur by changing the size limits of mongo's write cache.
