### ISSUE TITLE
CogniVideo UX Features - Counting Down Progress

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1334]
Need to add counting down to the question in the progress area screen. I would probably like to make this bigger than it currently is in the Mofacts system and I think we should try to have the countdown start at 10 seconds before the question (although I might change that later if it's not too hard).

**Comment by imrryr** [comment]
It seems the size of the countdown could be a ui parameter

So you mean the extra countdown would overlay the video?

**Comment by shelbik37** [comment]
I would like to see what it looks like in the position it currently is in Mofacts (at the bottom of the screen) but made bigger and have it start counting down 10 seconds before a question.

 I'm confident I don't want it to be overlayed on the video big, in the middle of the screen, but I might consider overlaying it on the video screen in the bottom right hand corner or something. 

I feel like it's something I need to see before making a final decision, so it seems easiest to just adjust the current UI parameter and then go from there. If that makes sense?
