### ISSUE TITLE
Doesn't give any practice

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1339]
It appears to be an error looking up the clusterlist to use to restrict the calculateProbabilities

![mofacts_app - Google Chrome 11_30_2023 5_42_11 PM](https://github.com/memphis-iis/mofacts/assets/13023147/71d82dc2-e335-491a-87de-53f240716eda)

**Comment by JRustyHaner** [comment]
@imrryr we were looking for the tdf in the session variables and it hadn't been set yet -- also this led to fixing another bug where hint calculations were happening where no hint probabilities were defined.
