### ISSUE TITLE
Skips learning sessions

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1341]
It goes right from the instructions to the survey in the next unit. Perhaps it thinks no items are available, e.g. if the clusterlist is not correctly loaded, bu still valid?

[OptimTester3 preflight.zip](https://github.com/memphis-iis/mofacts/files/13531418/OptimTester3.preflight.zip)

**Comment by JRustyHaner** [comment]
@imrryr while that was a problem, there's another: the currentDeliveryParameters.optimalThreshold was returning as 0

Math.log(0/1-0) gives -infinity, which is impossible to find distances for.

I don't know how you want to fix that, since I'm not sure you were aware that

**Comment by JRustyHaner** [comment]
@imrryr  I got it, the translation in currentTestingHelpers is running parseInt on it, 

The integer value of 0.7 is 0, leading to Math.log(0/1-0) to -Inf

**Comment by imrryr** [comment]
After thinking about this, if an experimenter leaves this unset, I think it is best considered a bug in the tdf and it should fail. So please make sure there is no default and it will error if this is not provided either in Parameters[1] or optimalThreshold
