### ISSUE TITLE
UI settings for text trials

### ISSUE THREAD

**Issue by Wei940127** [memphis-iis/mofacts#1342]
Could the study trial show the stimulus or text on the left, and the response on the right, and place both in the center of the page? Here's an image for reference.
![wanted study trial](https://github.com/memphis-iis/mofacts/assets/54991536/18b6c658-9cf7-474b-b812-6cc1715ef9f2)

Could the incorrect feedback include the correct response alongside the text? Here's an image for reference.
![wanted incorrect feedback](https://github.com/memphis-iis/mofacts/assets/54991536/443f2269-6b57-446b-8ffe-4bb79ef22c14)

Also, could the correct feedback include the correct response alongside the test? Here's an image for reference.
![wanted correct feedback](https://github.com/memphis-iis/mofacts/assets/54991536/2ac08e3f-d7c3-4bed-b6b1-267ba32f6fc9)
Thus, all response parts will be displayed within a highlighted grey area.

I used the following UI setting codes, and I also attached images to show what the interfaces look like after using these codes.
![UI settings now](https://github.com/memphis-iis/mofacts/assets/54991536/d7803c3d-507b-4c0a-9f59-97d47cfe106a)
![stimulusdisplay](https://github.com/memphis-iis/mofacts/assets/54991536/bffea1df-7098-4810-b1de-5ec387681a83)
![Incorrect feedback](https://github.com/memphis-iis/mofacts/assets/54991536/7e6dda96-acdf-4b1b-a121-d01912b21cea)

**Comment by imrryr** [comment]
It seems pretty straightforward: adapt the display for side-by-side presentation.

**Comment by imrryr** [comment]
Ack, this changed the defaults. As a rule, we can NEVER change the defaults without creating bugs in existing systems. The radicals experiment should not change as a function of this task. Please look into it.
