### ISSUE TITLE
new data needed for model p.overallStudyHistory

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1344]
This will contain the overall history for the learner like p.overallOutcomeHistory, but with a 1 for each study trial and a 0 for each success or failure trial

**Comment by imrryr** [comment]
This doesn't seem to provide overallStudyHistory, also my code calling it was not working. Please provide it here in these console outputs for checking aslo if it is working in other contexts.

For example, copied for console

answerText
: 
"halberd"
clusterIndex
: 
12
clusterOutcomeHistory
: 
[]
clusterPreviousCalculatedProbabilities
: 
(31) [0.009877310559999294, 0.009877310559999294, 0.009877310559999294, 0.009877310559999294, 0.014778765102238363, 0.01873228170042944, 0.01873228170042944, 0.022186964070316003, 0.022186964070316003, 0.025321773242573956, 0.025321773242573956, 0.028230134679139603, 0.028230134679139603, 0.028230134679139603, 0.03096825783173243, 0.03357312501955103, 0.03607062541619069, 0.03607062541619069, 0.03607062541619069, 0.03607062541619069, 0.038479730721785, 0.04081484170249863, 0.04308719977170954, 0.04308719977170954, 0.04308719977170954, 0.04308719977170954, 0.04530578262753169, 0.028439278439125932, 0.02198272171316279, 0.0231073746389156, 0.02421212587302715]
hintLevel
: 
0
i
: 
9
instructionQuestionResult
: 
null
overallOutcomeHistory
: 
(17) [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1]
pFunc
: 
{}
questionFailureCount
: 
0
questionSecsPracticingOthers
: 
0
questionSecsSinceFirstShown
: 
0
questionSecsSinceLastShown
: 
0
questionStudyTrialCount
: 
0
questionSuccessCount
: 
0
questionTotalTests
: 
0
resp
: 
{KCId: 145, hintLevel: null, priorCorrect: 0, allTimeCorrect: 0, allTimeIncorrect: 0, …}
responseFailureCount
: 
0
responseOutcomeHistory
: 
[]
responseSecsSinceLastShown
: 
0
responseStudyTrialCount
: 
0
responseSuccessCount
: 
0
stim
: 
{stimuliSetId: 87, stimulusFileName: 'Radicalstimsv3.json', stimulusKC: 870055, clusterKC: 870055, responseKC: 145, …}
stimFailureCount
: 
0
stimIndex
: 
0
stimOutcomeHistory
: 
[]
stimParameters
: 
(2) [-4.6075886, 0.7]
stimPreviousCalculatedProbabilities
: 
(31) [0.009877310559999294, 0.009877310559999294, 0.009877310559999294, 0.009877310559999294, 0.014778765102238363, 0.01873228170042944, 0.01873228170042944, 0.022186964070316003, 0.022186964070316003, 0.025321773242573956, 0.025321773242573956, 0.028230134679139603, 0.028230134679139603, 0.028230134679139603, 0.03096825783173243, 0.03357312501955103, 0.03607062541619069, 0.03607062541619069, 0.03607062541619069, 0.03607062541619069, 0.038479730721785, 0.04081484170249863, 0.04308719977170954, 0.04308719977170954, 0.04308719977170954, 0.04308719977170954, 0.04530578262753169, 0.028439278439125932, 0.02198272171316279, 0.0231073746389156, 0.02421212587302715]
stimResponseText
: 
"halberd"
stimSecsPracticingOthers
: 
0
stimSecsSinceFirstShown
: 
0
stimSecsSinceLastShown
: 
0
stimStudyTrialCount
: 
0
stimSuccessCount
: 
0
userCorrectResponses
: 
14
userTotalResponses
: 
16

**Comment by imrryr** [comment]
@JRustyHaner not seeing this working, still missing. Maybe the old code was posted? The other problem with stimPreviousCalculatedProbabilities also looked to be the same as before, with a much longer vector of the wrong values.

**Comment by JRustyHaner** [comment]
That's exactly what happened
