### ISSUE TITLE
buttontrial in learningsession unit fails (no trials)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1348]
from console:
showPerformanceDetails type: s
1c94e515186d18b01d7e37c64adb1855f8366835.js?meteor_js_resource=true:286 Uncaught (in promise) TypeError: e.buttontrial.toLowerCase is not a function
    at Qe (1c94e515186d18b01d7e37c64adb1855f8366835.js?meteor_js_resource=true:286:72009)
    at Je (1c94e515186d18b01d7e37c64adb1855f8366835.js?meteor_js_resource=true:286:73344)
    at Ke (1c94e515186d18b01d7e37c64adb1855f8366835.js?meteor_js_resource=true:286:73023)
    at async yt (1c94e515186d18b01d7e37c64adb1855f8366835.js?meteor_js_resource=true:286:95935)

package with problem:
[Unit1 (1).zip](https://github.com/memphis-iis/mofacts/files/13718258/Unit1.1.zip)

It was working until I turned on button trial

**Comment by JRustyHaner** [comment]
@imrryr this is that issue I mentioned where 'true' and true are not the same thing for isButtonTrial parameter. I have a PR to allow for both.

FYI/Fun Fact:  In Javascript, anything with triple equals is a type sensitive comparison.  So true (boolean) when compared to 'true' (string) will return false. With double equals, the same comparison returns true.

**Comment by imrryr** [comment]
Can we search the entire code base for a triple equal sign?

**Comment by JRustyHaner** [comment]
@imrryr in this context, it would be best to only change the triple equals to double equals when dealing with Tdf json. It looks like that was the only instance of that.  

Just looks like someone was trying to be fancier than they needed to be and in the result, broke something.

**Comment by imrryr** [comment]
Great thank you.
