### ISSUE TITLE
Scores did not show for practice in tdf

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1351]
Console error when looking up data for tdf assigned to class (I think data was gathered in experiment mode, but it should still come up and error appears unrelated).

![MoFaCTS - Google Chrome 12_25_2023 7_03_27 AM](https://github.com/memphis-iis/mofacts/assets/13023147/72c66e99-698d-4688-a203-9b00de5bd3c3)

**Comment by MegaGeese** [comment]
@imrryr looks like an issue with the db. I think I've resolved it but will need you to test it.
It should show up after you log into the class and section with the test user that you did the trials on.

**Comment by imrryr** [comment]
So I will test it (is in production or staging)? I guess I should have marked this issue and the others I realize as production and staging...

**Comment by MegaGeese** [comment]
Since the url was 'mofacts.optimallearning.org' I assumed we were talking about production. Staging did not have the missing table in the database when I checked so this should be a bug exclusive to production.

**Comment by imrryr** [comment]
I created a new issue, this did not work on staging. @MegaGeese
