### ISSUE TITLE
Class login does not show teacher names

### ISSUE THREAD

**Issue by MegaGeese** [memphis-iis/mofacts#1355]
![Screenshot 2024-01-02 104431](https://github.com/memphis-iis/mofacts/assets/50426711/b7fc4b21-617b-4803-9c79-7195577a0018)

**Comment by imrryr** [comment]
Why would or should it do this? Seems unneeded and hard for students.

**Comment by imrryr** [comment]
I do find this login screen kinda confusing. Students will initially have problems if they have to select the teacher before logging in... Can it be after? It doesn't really seem the sort of thing that is standard on a login screen to me.

**Comment by JRustyHaner** [comment]
@imrryr this was the flow design of mofacts originally when looking up teachers. Yes, two teachers can each create a class with the same name.

If you want to change the flow to something like this:

Login >> Select Class/Teacher  

We need to discuss where we put the option to select a teacher/class on the profile or main menu.

**Comment by imrryr** [comment]
If they log in with the classroom link, wouldn't it be possible for a
pop-up just to occur if there were more than one class, after the login?

**Comment by JRustyHaner** [comment]
@imrryr if they're using a link, they won't be asked at all, since the link selects the class and teacher for them.

**Comment by JRustyHaner** [comment]
@imrryr It isn't possible for a single teacher to create two classes with the same name. Sorry, I should have told you that.

**Comment by imrryr** [comment]
So, so this class login button is only if they don't use the link then? @Rusty
Haner ***@***.***>

**Comment by JRustyHaner** [comment]
@imrryr That's correct. The reason why the button is there in the first place is just in case someone is using an app version or doesn't have a teacher/class link. Meteor phone apps do not accept hyperlinks as parameters.

Although, it may be less confusing to detect if a link was used and then hide the teacher select button.
