### ISSUE TITLE
Missing correct and incorrect feedback messages during drill trials

### ISSUE THREAD

**Issue by Wei940127** [memphis-iis/mofacts#1357]
I used the following codes and found no correct or incorrect feedback messages were displayed, either indicating correctness or incorrectness, during drill trials after participants entered their responses. 
![image](https://github.com/memphis-iis/mofacts/assets/54991536/709ff120-e96b-42d0-af7f-2afed4e68fa0)
Here is the interface I've got after both correct and incorrect attempts.
![Missing part of feedback](https://github.com/memphis-iis/mofacts/assets/54991536/251cddf6-7a7e-493e-ade1-f72e86bf87ff)

Below are the interfaces I'd like to use for the experiment which indicate correct and incorrect attempts. Could you help me with it? Thanks!
![correct interface](https://github.com/memphis-iis/mofacts/assets/54991536/53d6cda3-072c-467a-a315-f3ab85b62ad2)
![incorrect interface](https://github.com/memphis-iis/mofacts/assets/54991536/15b52b97-a025-49cb-9aa8-2fc85bacb25b)

**Comment by imrryr** [comment]
We need to make sure we are using staging and production correctly. Maybe we should make sure all the changes from the various issues go to staging, and then test and do a production deploy next week? @JRustyHaner @MegaGeese Thanks!

**Comment by imrryr** [comment]
@Wei940127 Please supply the uisettings json in json, not an image please. images are hard to copy and test.

**Comment by Wei940127** [comment]
Below are the files I used for the test.
[HighMTestPractice (7).zip](https://github.com/memphis-iis/mofacts/files/13815481/HighMTestPractice.7.zip)

Here are the codes for the UI setting.
```
            "uiSettings": {
              "displayReviewTimeoutAsBarOrText": "false",
              "displayReadyPromptTimeoutAsBarOrText": "false",
              "displayCardTimeoutAsBarOrText": false,
              "displayTimeOutDuringStudy": false,
              "displayUserAnswerAtTop": false,
              "displayPerformanceDuringStudy": true,
              "displayCorrectAnswerInCenter": true,
              "displayUserAnswerInFeedback": true,
              "onlyShowSimpleFeedback": false,
	      "stimuliPosition":"left",
              "incorrectColor": "darkorange",
              "correctColor": "green"
            }
```

**Comment by JRustyHaner** [comment]
@Wei940127 @imrryr 

This is an old specification.  Please use the following options and tailor them to your needs:

      "displayReviewTimeoutAsBarOrText": "both"
      "displayReadyPromptTimeoutAsBarOrText": "both",
      "displayCardTimeoutAsBarOrText": "both",
      "displayTimeOutDuringStudy": true,
      "displayUserAnswerInFeedback": true,
      "displayPerformanceDuringStudy": false,
      "displayPerformanceDuringTrial": true,
      "displayCorrectAnswerInCenter": false,
      "singleLineFeedback" : false,
      "feedbackDisplayPosition" : "middle",
      "stimuliPosition" : "top",
      "choiceButtonCols": 1,
      "onlyShowSimpleFeedback": false,
      "incorrectColor": "darkorange",
      "correctColor": "green"

**Comment by JRustyHaner** [comment]
@imrryr @Wei940127 We have a pull request for this issue. 

The UI Settings are now correct.

**Comment by imrryr** [comment]
@JRustyHaner @MegaGeese So can we plan to deploy tomorrow to staging with all current changes, please?

**Comment by JRustyHaner** [comment]
@imrryr Sure, when all the PRs are pulled in.

**Comment by imrryr** [comment]
Right, thank you..

**Comment by Wei940127** [comment]
I just tested it and the feedback display worked correctly. 
![image](https://github.com/memphis-iis/mofacts/assets/54991536/579ac4f2-3295-407d-a778-4c8913674298)
But the typing bar still missing.
![image](https://github.com/memphis-iis/mofacts/assets/54991536/b3a4c249-a6db-4951-a276-8210e1bced27)

**Comment by JRustyHaner** [comment]
@imrryr @Wei940127 closing this as complete

**Comment by imrryr** [comment]
@JRustyHaner It seems you closed this. Did you want another issue created or can we respond to Wei's reply here. She posted it to minutes before you closed it and I'm guessing you didn't see it when you closed it.

**Comment by Wei940127** [comment]
Sure. Here is the file. Thank you!
[HighMTestPractice13.zip](https://github.com/memphis-iis/mofacts/files/13844249/HighMTestPractice13.zip)

**Comment by JRustyHaner** [comment]
@imrryr I'll just work off of this issue request
