### ISSUE TITLE
Can't login at either MS or google login for class link

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1361]
![Screenshot (147)](https://github.com/memphis-iis/mofacts/assets/13023147/1a24ee5c-3b96-4dd5-a43d-9b58673adf4f)
![MoFaCTS - Google Chrome 1_6_2024 11_48_43 AM](https://github.com/memphis-iis/mofacts/assets/13023147/43655c7f-3510-4163-a755-a01949a948a5)

**Comment by imrryr** [comment]
I was able to login with the regular login link, and the tdf did complete when I ran with the experiment link, so this seems clearly the student class login not working.

**Comment by imrryr** [comment]
[unit1.zip](https://github.com/memphis-iis/mofacts/files/13850704/unit1.zip)

**Comment by imrryr** [comment]
This isn't working at all for e.g. http://staging.optimallearning.org/classes/imrryr@gmail.com/vyPMeA75nmrFesQPf
7302 Test
@JRustyHaner

**Comment by JRustyHaner** [comment]
@imrryr that is an unsecure link. It appears if the class link generator produces links that begin with http instead of https. If it isn't https, Microsoft is not going to like it.

Try https://staging.optimallearning.org/classes/imrryr@gmail.com/vyPMeA75nmrFesQPf

**Comment by JRustyHaner** [comment]
@imrryr I'll make a PR to have the class link generator show https

**Comment by imrryr** [comment]
Did this get done? Because it seemed to work fine just now...
