### ISSUE TITLE
Class practice data does not show for practice in tdf

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1362]
This still fails. Of course, I was only able to generate experiment link data since I could not login to the classroom version link
![MoFaCTS - Google Chrome 1_6_2024 12_02_54 PM](https://github.com/memphis-iis/mofacts/assets/13023147/d9ff6744-9b22-42ce-948e-ae3f00f5890c)

**Comment by imrryr** [comment]
Did staging get deployed before this was fixed? I still see this same error.

**Comment by MegaGeese** [comment]
Yes, I havent been able to sort out the issue with this quite yet.

**Comment by MegaGeese** [comment]
Also should experiment link data be shown on this page? Since it wouldn't necessarily be associated with a class.

**Comment by imrryr** [comment]
As it turns out, the classroom link is still broken..., so I still can't produce data that should show here (though Augustyou had implied before that you had made experiment link data show here, so I was looking for that)....  How are you generating student data to test this? @MegaGeese Seems a necessary step in fixing it. This may require the student login to be working. @JRustyHaner Rusty, how are you testing the student login?

**Comment by MegaGeese** [comment]
![image](https://github.com/memphis-iis/mofacts/assets/50426711/01d921ff-7822-41d3-8f12-e0c25a22905f)
Im able to get experiment data to show. I just logged in by clicking "Teacher/Class Select" then selecting your email and section, then logging in normally. After doing 4 trials this was what was shown on the report

**Comment by imrryr** [comment]
I will try it that way. I do see your data when I login. I had forgotten this indirect login method. Thanks. So maybe it is only the direct login links that are not working then @JRustyHaner

**Comment by JRustyHaner** [comment]
@imrryr Possibly.  Not quite sure though, so I'd leave this open until you've tested it. The issue was with the link that was generated for you for the class login was missing the 's' in https.

**Comment by imrryr** [comment]
I just tested. It appeared to work perfectly! Thanks to you both!
