### ISSUE TITLE
Crashed the content uploader

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1365]
It no longer shows any content. I was trying to simultaneously upload 5 zip files. It appeared they were uploading (due to popups), but then this. Please reset it somehow. Also, disable multi file upload, unless it is easy to make it reliable. I was having no problem until I tried this. Please help soon if possible since I plan to use the system in my course next week (starting Tuesday) and I need to test these files and have them running. @JRustyHaner @MegaGeese 
![295999744-783db215-e73a-4d2b-a66b-42fd8294d11f png (1920×1080) - Google Chrome 1_11_2024 11_29_13 AM](https://github.com/memphis-iis/mofacts/assets/13023147/f62f7513-d927-40a0-a4c2-749c5241d8b2)
![MoFaCTS - Google Chrome 1_11_2024 11_21_26 AM](https://github.com/memphis-iis/mofacts/assets/13023147/5d93c2e0-19cf-4bf0-9c84-eaaca8ceaa39)
[unit4.zip](https://github.com/memphis-iis/mofacts/files/13906437/unit4.zip)
[unit5.zip](https://github.com/memphis-iis/mofacts/files/13906438/unit5.zip)
[unit1.zip](https://github.com/memphis-iis/mofacts/files/13906439/unit1.zip)
[unit2.zip](https://github.com/memphis-iis/mofacts/files/13906441/unit2.zip)
[unit3.zip](https://github.com/memphis-iis/mofacts/files/13906443/unit3.zip)

**Comment by imrryr** [comment]
Also blocks new uploads...
![295999744-783db215-e73a-4d2b-a66b-42fd8294d11f png (1920×1080) - Google Chrome 1_11_2024 11_30_43 AM](https://github.com/memphis-iis/mofacts/assets/13023147/55f2a6aa-74ba-4c46-ab4b-e8bda4e187ee)

**Comment by JRustyHaner** [comment]
@imrryr looks like I am going to  have to clean the database, was there any current data on there?

**Comment by imrryr** [comment]
shouldn't be. What happened?

**Comment by JRustyHaner** [comment]
@imrryr It looks like that the queue isn't being processed correctly. I'm looking into a fix for that, so please upload one at a time for now, once I clean the dataset.

**Comment by JRustyHaner** [comment]
@imrryr cleaned the dataset, you're good to start uploading again

**Comment by JRustyHaner** [comment]
I'm going to disable that feature and deploy today.

**Comment by JRustyHaner** [comment]
@imrryr This has been patched out. You can no longer upload multiple packages at the same time
