### ISSUE TITLE
Package won't upload

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1368]
[Radicalroot.zip](https://github.com/memphis-iis/mofacts/files/13932177/Radicalroot.zip)
Error in console.
![MoFaCTS - Google Chrome 1_14_2024 10_12_09 AM](https://github.com/memphis-iis/mofacts/assets/13023147/9e7187e6-08ca-41b6-b5d0-139282d30edb)

**Comment by JRustyHaner** [comment]
Theres an error in the Radicalroot.json. A } in the wrong place.

 Wed Jan 17 2024 10:22:00 GMT-0600 (Central Standard Time) 3 processPackageUpload ERROR, /home/vagrant/dynamic-assets/xugs4PNDh6Xb8mpkN.zip , SyntaxError: Unexpected token } in JSON at position 443 on file: Radicalroot.json

**Comment by imrryr** [comment]
thanks!
