### ISSUE TITLE
Content uploader fails at some point

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1370]
I uploaded this zip with correct json
[Radicalroot.zip](https://github.com/memphis-iis/mofacts/files/13991058/Radicalroot.zip)

It flashed some uploads, then settled on this screen; I seem to have corrupted it badly enough that it is broken. Help me please.

![MoFaCTS - Google Chrome 1_19_2024 9_27_50 AM](https://github.com/memphis-iis/mofacts/assets/13023147/e06129a6-acf4-4eba-b6a5-0ec963ff7fa6)

**Comment by JRustyHaner** [comment]
Looking into this, but I'm having trouble connecting to the VPN right now

**Comment by JRustyHaner** [comment]
Mevermind

**Comment by JRustyHaner** [comment]
@imrryr builing a  solution, will package it with PR #1369

**Comment by JRustyHaner** [comment]
@imrryr deployed, looks like it shows in your content management page
