### ISSUE TITLE
tdf does not start up

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1371]
tdf does not start up. the experiment page loads, then this happens after turk login. No units were started.
[Radicalroot.zip](https://github.com/memphis-iis/mofacts/files/13992882/Radicalroot.zip)

**Comment by imrryr** [comment]
![MoFaCTS - Google Chrome 1_19_2024 12_21_00 PM](https://github.com/memphis-iis/mofacts/assets/13023147/9203b81a-902b-4a7a-8e2d-c1796040944a)

**Comment by JRustyHaner** [comment]
@imrryr  the correct values for loadbalancing are min or max. It will also not work  Your json has it set to true.
also, your  setspec.countcompletion value is not set.  This must be "beginning", "end", or a unit number. 

See https://github.com/memphis-iis/mofacts/pull/1322

**Comment by imrryr** [comment]
{
        "unitname": "Final",
        "unitinstructions": "<p>Your answers have been submitted. Thank you for participating in this challenging study of learning and assessment. Your account will be credited with the bonus after we check your results.</p>",
        "countcompletion": true
      }

**Comment by JRustyHaner** [comment]
@imrryr well, json when something is unset, it's false/undefined/null. Javascript doesn't really see a difference between those.  If you have a unit with countcompletion true, then it should work.

**Comment by JRustyHaner** [comment]
@imrryr to answer your question, don't set a setspec.countcompletion if you are using unit.countcompletion.

**Comment by imrryr** [comment]
I made the wiki a bit clearer too.
