### ISSUE TITLE
Typo causes loadbalancing to fail "setpec"

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1372]
let e = 1e9
                                              , t = [];
                                            for (condition in n.condition)
                                                conditionCounts[condition] < e && (e = conditionCounts[condition]);
                                            for (condition in n.condition)
                                                conditionCounts[condition] == e && t.push(setpec.condition[condition]);
                                            0 == t.length && (t = n.condition);
                                            const s = _.sample(t);
                                            r = Tdfs.findOne({
                                                "content.fileName": s
                                            })._id

**Comment by imrryr** [comment]
This one seems pretty straightforward.

**Comment by imrryr** [comment]
super! can we deploy to both mofacts and staging? I want the skipstudy changes on mofacts for my class please.

**Comment by JRustyHaner** [comment]
@imrryr sure

**Comment by JRustyHaner** [comment]
@imrryr @JRustyHaner @MegaGeese this is a reminder that the production server will be running branch iss1366 until a merge from a code review.
