### ISSUE TITLE
multitdfs aren't working

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1373]
both Blake and I can't make it run. Here is my info 
[Radicalroot.zip](https://github.com/memphis-iis/mofacts/files/14012648/Radicalroot.zip)

![image](https://github.com/memphis-iis/mofacts/assets/13023147/b93b0523-4273-4cac-a818-debfbd37f6e9)

**Comment by JRustyHaner** [comment]
@imrryr loadbalancing cannot be true, it must be min or max.

**Comment by imrryr** [comment]
Still not working. I tried it without reuploading, and that failed, then tried to reupload, and that failed like this
![image](https://github.com/memphis-iis/mofacts/assets/13023147/eb9a4edc-1bda-46fb-a8b1-f4e76efab603)
![image](https://github.com/memphis-iis/mofacts/assets/13023147/eca4f30a-4669-4d20-bb4f-c9df0438bd7d)

**Comment by imrryr** [comment]
@JRustyHaner still some problem

**Comment by imrryr** [comment]
Whoops this is a general problem on both servers now @JRustyHaner @MegaGeese Its happening for these tdfs also
[unit1.zip](https://github.com/memphis-iis/mofacts/files/14015456/unit1.zip)
[unit2.zip](https://github.com/memphis-iis/mofacts/files/14015457/unit2.zip)
e.g.
![image](https://github.com/memphis-iis/mofacts/assets/13023147/ba26ec86-1dbb-49f5-9e9f-0ddce783d362)

**Comment by imrryr** [comment]
I made a new issue. I'll test this issue after uploading is working, but the multitdfs didn't start working before the upload (mutlitdf that is)
