### ISSUE TITLE
study trial fails in tdf of package

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1376]
[RadicalLevels879.json](https://github.com/memphis-iis/mofacts/files/14015855/RadicalLevels879.json)
starts up well, but the first trial errors our when practice begins
![image](https://github.com/memphis-iis/mofacts/assets/13023147/09e8c84b-0998-4d9a-9024-9713316b6cc2)

**Comment by imrryr** [comment]
it was in this tdf, unit 3 that failed.
[RadicalLevels879.json](https://github.com/memphis-iis/mofacts/files/14015884/RadicalLevels879.json)
the quiz tdf uploaded and ran fine on my last test :)

**Comment by JRustyHaner** [comment]
I saw that, it was looking for a variable that didn't exist.


Just trying to get you ready for class

**Comment by JRustyHaner** [comment]
@imrryr it'll run all the way through
