### ISSUE TITLE
cards not loading for assessment unit

### ISSUE THREAD

**Issue by Wei940127** [memphis-iis/mofacts#1384]
There seems something wrong with the assessment unit. The drill cards cannot be loaded. Not sure which part of my codes caused it. Have attached the screenshot and .zip file below.

[Meaningfulstims (2).zip](https://github.com/memphis-iis/mofacts/files/14089401/Meaningfulstims.2.zip)
![Screenshot 2024-01-29 144610](https://github.com/memphis-iis/mofacts/assets/54991536/c4d6eb12-c520-4a26-a142-7b63ab1441bb)

**Comment by imrryr** [comment]
"permutefinalresult":"6-23", is incorrect, your initial positions has 18 items so "permutefinalresult":"0-17",
