### ISSUE TITLE
Load balancer not counting runs

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1389]
Not showing anything in Wei's counters after 32 runs.... 
[HMRT4_count1.zip](https://github.com/memphis-iis/mofacts/files/14115296/HMRT4_count1.zip)
Please check if this should be working. It seems exactly correct to me.

**Comment by imrryr** [comment]
Wei just tried it again, but it did not work. Please share your recent zip file here Wei @Wei940127 @JRustyHaner @Brtelfer

**Comment by Wei940127** [comment]
Here is the file used for the test.
[LMRT1c.zip](https://github.com/memphis-iis/mofacts/files/14142001/LMRT1c.zip)

**Comment by JRustyHaner** [comment]
@imrryr I have a solution for this that I tested with the new package locally. How time sensitive is this for deployment?

**Comment by imrryr** [comment]
Well, there are 3 experiments waiting on it. None of them have near deadlines though if you are putting out other fires. @JRustyHaner

**Comment by JRustyHaner** [comment]
@imrryr  I wanted to know if you needed them before a review happened. No fires to be put out elsewhere at the moment.

**Comment by JRustyHaner** [comment]
@imrryr sure, I have a PR for it #1392

**Comment by Wei940127** [comment]
I just tried it with `loadbalancing: "min"`, and it seems not working. Below are the results and files. When I tested it, I used the incognito mode of Chrome, not sure if it matters. 
![Screenshot 2024-02-07 105329](https://github.com/memphis-iis/mofacts/assets/54991536/d84e8cb7-8963-49d1-9bc5-e75abea504ef) 
![counttestmin0207](https://github.com/memphis-iis/mofacts/assets/54991536/2356ea8e-4692-42bb-aa39-70810eb35dfa)
[LMRT2count3.zip](https://github.com/memphis-iis/mofacts/files/14200047/LMRT2count3.zip)

**Comment by imrryr** [comment]
When they are closed it does not mean they are ready yet.
