### ISSUE TITLE
uploader broken on staging

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1397]
![image](https://github.com/memphis-iis/mofacts/assets/13023147/89d020f3-9afe-450c-9eae-c601d972fd5e)

**Comment by imrryr** [comment]
stopped working after reuploading this
[unit11.zip](https://github.com/memphis-iis/mofacts/files/14172145/unit11.zip)

**Comment by JRustyHaner** [comment]
@imrryr   We get that link from the filename of the package. The package update might not change the package's filename in the database.  Since we were looking for that package filename, and it had been replaced, it returned undefined, which breaks the page. I'll look into it in the morning.
