### ISSUE TITLE
Unti 12 worked, but Unit 11 produced this failure

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1398]
It is mentioning video units, but Unit 11 is normal content, no videos. This happens immediately on start. @MegaGeese 

![image](https://github.com/memphis-iis/mofacts/assets/13023147/1fc854ad-5ede-499f-bd2a-ba379f55421c)

**Comment by JRustyHaner** [comment]
@imrryr could you send me unit 11's package  please?

**Comment by JRustyHaner** [comment]
@imrryr also for some reason I cannot reproduce this error with a fresh account.

**Comment by imrryr** [comment]
@JRustyHaner it still happens for me. I can bring my computer later. I think it seemed associated with how the uploader failed when I uploaded it #1397 
[unit11.zip](https://github.com/memphis-iis/mofacts/files/14196661/unit11.zip)

**Comment by JRustyHaner** [comment]
@imrryr I'll look into it. The variable in question is the current unit number. On line 3307,  Session.get('currentTdfFile').tdfs.tutor.unit[Session.get('currentUnitNumber')] returns undefined since Session.get('currentUnitNumber')]  is sometimes set to 1, and that tdf only appears to have a unit 0.

**Comment by imrryr** [comment]
When a tdf completes, it should retain the unitnumber in the database. If 0 is first unit, if I did 11 on that user with the old version that user will be set to 1, which would result in the tdf not running.... That is expected behavior.

However, that is not what production is doing, currently on production it seems to be not incrementing the unit number and students can run the same prequiz twice... perhaps it doesn't increment the unit number if there is no next unit? It really should otherwise this unintended rerunning of experiments becomes possible @JRustyHaner

**Comment by imrryr** [comment]
So basically I would not have reported this unless I had become used to what I might have considered a bug. Basically this is a problem with the resume function because if a user completes a unit, it should not restart with that unit. (though it should restart if the unit is not complete of course as usual)

**Comment by JRustyHaner** [comment]
@imrryr FYI  the current unit number session variable is only set at the end of the previous unit or a resume from component state, or when a user navigates away from the page.

**Comment by imrryr** [comment]
@JRustyHaner what are the implications of that relative to what I said?

**Comment by imrryr** [comment]
We have to load the current unit number on each tdf start

**Comment by JRustyHaner** [comment]
@imrryr did you happen to encounter a continue button that you used on card?

**Comment by imrryr** [comment]
huh? the practice just ends in assessment sessions.... (like the prequiz)

**Comment by JRustyHaner** [comment]
@imrryr just exploring avenues.  I  can't reproduce it on this end with the existing deployment on staging or on a local copy, but I've seen this error before. It's intermittent it seems, so I'm trying to figure out the exact condition that causes it.

**Comment by imrryr** [comment]
Well we're meeting in person at 3:00 and so why don't we look at my
computer then because it still produced it.

**Comment by imrryr** [comment]
well, so does that imply that it can't resume an assessment session since after the instructions any resume will go to the next unit? I think we used to save the progress in the schedule, and resumed the schedule

**Comment by JRustyHaner** [comment]
@imrryr Very well, I have a PR up.
