### ISSUE TITLE
Reloading assessment sessions for multiple choice causes wrong answer to be miss assigned on resume

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1403]
A problem on both staging and mofacts, so it isn't from the most recent changes, and may be old. I expect it general to all assessment sessions for multiple choice on resume.

![Screenshot 2024-02-18 151332](https://github.com/memphis-iis/mofacts/assets/13023147/2e6b27af-e1d2-47ff-916e-ce18d8e49674)
![Screenshot 2024-02-18 150940](https://github.com/memphis-iis/mofacts/assets/13023147/cdc3e513-045c-44dd-ba59-8017bf7e3a42)

**Comment by imrryr** [comment]
You can see the correct answer appears to be always there, but the wrong answers are coming from other items

**Comment by imrryr** [comment]
@MegaGeese this seems to be a backend task you will understand. Thanks for your help with it. It may be just redoing or ignoring other randomization on reload (but only for the wrong answers?

**Comment by imrryr** [comment]
@this pull request appears to be improperly linked @JRustyHaner

**Comment by JRustyHaner** [comment]
It is, GitHub is being a pain when I unlink it. @imrryr
