### ISSUE TITLE
Missing instruction page at the end of Part 1.

### ISSUE THREAD

**Issue by Wei940127** [memphis-iis/mofacts#1405]
The instruction page which should be presented at the end of Part 1, including the experiment code is missing. Here is the screenshot for this issue.
![Screenshot 2024-02-21 091332](https://github.com/memphis-iis/mofacts/assets/54991536/6b9a3e2c-a0bf-4712-a24c-856b462652fd)

Here is the package I used for the testing.
[LMRT2c7finalinstruction.zip](https://github.com/memphis-iis/mofacts/files/14361361/LMRT2c7finalinstruction.zip)

**Comment by imrryr** [comment]
@JRustyHaner @Wei940127 the experiment code is simply in the instructions you made. It is not from the system, so the bug is that the instructions don't show.... it goes right to this screen.
