### ISSUE TITLE
CogniVideo Experiment Video Play bug

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1420]
The video player in the experimental group isn't showing any video controls, so I can't FF, Rewind, Scrub, Pause, etc...

**Comment by MegaGeese** [comment]
You mean the video playbar like this isn't showing? 
![image](https://github.com/memphis-iis/mofacts/assets/50426711/b9f955aa-2c8b-483d-a13f-ca17d7766049)

**Comment by shelbik37** [comment]
Yes, that isn't showing up. You can tap on the video in the middle of it to play/pause but no progress bar at the bottom where you can rewind and etc..
