### ISSUE TITLE
Question + Potential Addition

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1428]
I realized I meant to ask this during our meeting and forgot. It would be ideal if students could move back and forth through the video pages and the text + image pages. So, there is not only a "continue" button, but there is also a "back" button once they start on the learning pages. Is this a current spec that could be added? If not, would that be something particularly challenging and not possible to do before launching?

**Comment by imrryr** [comment]
Nice idea! Maybe even back-and-forward arrows in the bottom right corner? 
This might be a lot of work, but it isn't clear to me how the unit sequencing really works.
