### ISSUE TITLE
Plyr intermittingly cant read .volume 

### ISSUE THREAD

**Issue by JRustyHaner** [memphis-iis/mofacts#1430]
**Describe the bug**
Plyr will sometimes not read the .volume or .speed property on starting a new card. This occurs after the first card that contains a plyr video

**To Reproduce**
1. Cognivideo experiment mt2
2.  click continue after watching the first video

**Expected behavior**
Should continue to the next card without error

**Comment by shelbik37** [comment]
@JRustyHaner I just tested this and the continue button doesn't seem to be working once I get through the first video (I changed the volume and speed on the video while watching). You can click the button and it changes colors, but it does not actually progress forward.

**Comment by JRustyHaner** [comment]
@shelbik37 I've got a hotfix for it, building a solution now.
