### ISSUE TITLE
CogniVideo back button

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1431]
**Describe the bug**
The back button is appearing but not working in the control or experiment groups

**To Reproduce**
1. Go to cognivideo.org/experiment/mt1
3. Click 'continue'
5. Click on 'back arrow'
6. Nothing happens

**Expected behavior**
Page should go to the previous one

**Comment by JRustyHaner** [comment]
@shelbik37 Did you press the continue button then the back button?

**Comment by shelbik37** [comment]
@JRustyHaner yes

**Comment by JRustyHaner** [comment]
@shelbik37  That is issue #1430 then. The continue button is breaking the player.

**Comment by shelbik37** [comment]
@JRustyHaner To clarify - I pressed continue and it moved to the next page, then I hit back on the new page but it didn't actually go back to the previous page.

**Comment by shelbik37** [comment]
Oh, I see! I didn't realize they were the same issue. We can probably close this one then? FYI that if the back button is breaking things too much and it's going to take longer than ~today to fix it, we can remove the back button.

**Comment by JRustyHaner** [comment]
@shelbik37 It's the continue button breaking, sadly which is high priority. The back button is seperate.

**Comment by shelbik37** [comment]
Yep!

Shelbi L. Kuhlmann, PhD
Assistant Professor of Cognitive Psychology
Institute for Intelligent Systems
she/her/hers
[https://www.memphis.edu/emailsignatures/images/uofmlogo.jpg]   The University of Memphis

Psychology 442
Memphis, TN 901.678.2145
[UofM Facebook]<https://www.facebook.com/uofmemphis>  [UofM Twitter] <https://twitter.com/uofmemphis>   [UofM Instagram] <https://www.instagram.com/uofmemphis/>
________________________________

**Comment by shelbik37** [comment]
Sounds good - thanks for clarifying 🙂 I'll hold off on testing again until there's an update on the continue button.

Shelbi L. Kuhlmann, PhD
Assistant Professor of Cognitive Psychology
Institute for Intelligent Systems
she/her/hers
[https://www.memphis.edu/emailsignatures/images/uofmlogo.jpg]   The University of Memphis

Psychology 442
Memphis, TN 901.678.2145
[UofM Facebook]<https://www.facebook.com/uofmemphis>  [UofM Twitter] <https://twitter.com/uofmemphis>   [UofM Instagram] <https://www.instagram.com/uofmemphis/>
________________________________

**Comment by JRustyHaner** [comment]
@shelbik37 I've got a solution, I'm going to build it now for the sake of time.
