### ISSUE TITLE
Post-test trials cannot be loaded for returned participants.

### ISSUE THREAD

**Issue by Wei940127** [memphis-iis/mofacts#1438]
When the participants returned and typed in their ID, the free recall trials could not be presented. The following is the console screenshot. This didn't happen before.
![Screenshot 2024-03-20 112846](https://github.com/memphis-iis/mofacts/assets/54991536/08565cb6-a1dd-4b15-b619-263457b85f4e)

**Comment by imrryr** [comment]
Is this a bug for 1 person, or multiple? send the tdf and indicate the name of the unit that is not showing.

**Comment by Wei940127** [comment]
This occurs for one person, and the ID is A1LI3JQS2VBOXC. I tried another ID on my computer, and it works. Not sure what's going on.
