### ISSUE TITLE
Audio error for non audio tdf and stims

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1457]
My stim file or tdf is suddenly throwing this error. It all worked for a set of only 10 stims, could a bug in one of the 300 stims I added cause this... 

![image](https://github.com/memphis-iis/mofacts/assets/13023147/5615932e-d52c-4645-8fb8-2d8fb472b418)
[statsadaptmc.zip](https://github.com/memphis-iis/mofacts/files/14886891/statsadaptmc.zip)

**Comment by JRustyHaner** [comment]
@imrryr this occurse because stimDisplayTypeMap[currentStimuliSetId] is undefined. JavaScript can't check for hasAudio here, because its parent doesn't exist. I'll take a look more into it.

**Comment by MegaGeese** [comment]
I've seen this error but it usually only happens shortly after uploading/overwriting the tdf package. Just to confirm did you upload/overwrite the tdf right before this error appeared?

**Comment by imrryr** [comment]
Yes indeed that is what I did right before.

**Comment by imrryr** [comment]
@MegaGeese @JRustyHaner Can I fix this just be changing the filename or something? Or can we deploy if not please? This is MOFACTS2  only at this time

**Comment by MegaGeese** [comment]
it should fix itself if you refresh the browser

On Apr 5, 2024, at 1:32 PM, Philip Pavlik ***@***.***> wrote:

﻿
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and trust the content is safe.


@MegaGeese<https://github.com/MegaGeese> @JRustyHaner<https://github.com/JRustyHaner> Can I fix this just be changing the filename or something? Or can we deploy if not please? This is MOFACTS2 only at this time
