### ISSUE TITLE
Screen is not adjusting for monitor size and does not provide a scrollbar to indicate that things don't fit

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1461]
So, on some screen sizes, the MC questions are unreadable, and it appears the info is just missing for some buttons. Noelle showed me. Let's get a screenshot from her since I cannot reproduce it. Noelle, can you drag and drop a screenshot into the comment box?

**Comment by noelle453** [comment]
![Screenshot 2024-04-08 104621](https://github.com/memphis-iis/mofacts/assets/146384227/2a82c6e0-14db-4296-a4c2-2b08c159b929)

**Comment by noelle453** [comment]
This is how it looked after I scrolled down as far as possible.
