### ISSUE TITLE
CF (Entry Point)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1464]
Not correctly filled in with the entry point

direct is from lesson menu (marked incorrectly)
experiment would be from experiment links (not marked)
class is also not filled in would be from screens for classroom login links

**Comment by imrryr** [comment]
[mofacts_imrryr@gmail.com_all_tdf_data (15).txt](https://github.com/memphis-iis/mofacts/files/14979646/mofacts_imrryr%40gmail.com_all_tdf_data.15.txt)
[unit6-data (1).txt](https://github.com/memphis-iis/mofacts/files/14979647/unit6-data.1.txt)

**Comment by MegaGeese** [comment]
You're saying in this case it should be marked as "experiment" but instead it is being marked as "direct"?

**Comment by imrryr** [comment]
actually, the mofacts file 15 is the case where the turk users are not marked as coming from experiment, and the unit is a case where students are not marked coming from course links
