### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1485]
Shelbi cannot login anymore but I 100% know it's my Memphis email and I've tried every possible password, so I'm not sure what's going on. 

Can we add a reset/forgot my password button?

**Comment by MegaGeese** [comment]
There is a reset password page but it seems like it is not easily accessible. I can add a link to it on the login page

[prod](https://mofacts.optimallearning.org/resetPassword)
[staging](https://staging.optimallearning.org/resetPassword)

**Comment by JRustyHaner** [comment]
it would be cognivideo.com/resetPassword, and since she doesn't have email set up, the reset will not work.

**Comment by imrryr** [comment]
yes, add it to the login page please
