### ISSUE TITLE
Missing Continue Button on Participant ID Screen

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1486]
**Describe the bug**
Sometimes the CONTINUE button does not show up on the screen where a participant enters their ID. If this happens, we can typically type in the ID and hit the ENTER key. It would be ideal if the CONTINUE button always appeared though. 

However, there was one time where there was (1) no CONTINUE button and (2) the ENTER key did not progress the screen forward. At that time, we had to go back to the main menu, press LESSON SELECT and then enter the study that way (which worked).

**Comment by imrryr** [comment]
Typically this means you are still logged in. I haven't seen it otherwise. Can you reproduce it when you are sure you are logged in? Nevertheless, it would be nice to have fixed, so that it can't allow the fake login. Actually, I thought it was fixed. What server are you on?

**Comment by shelbik37** [comment]
Ah, this is on my CogniVideo server - so maybe it is fixed but it hasn't been pushed out to the CogniVideo server? I'm pretty sure I wouldn't have been logged in because it was on a participant computer in the lab. I also haven't been able to login because the system isn't taking my password. When we fix the password issue, I can try to recreate this while being logged in.

**Comment by shelbik37** [comment]
I did just access the experiment while 100% not being logged into CogniVideo and the CONTINUE button didn't appear.

**Comment by imrryr** [comment]
You may need to demonstrate that for the developers to help them track it down. This has been a persistently difficult issue to address for some reason.

**Comment by JRustyHaner** [comment]
It does
