### ISSUE TITLE
Button trials not working

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1496]
Can't figure it out. the button trials here [TDFpp.zip](https://github.com/user-attachments/files/15887017/TDFpp.zip) are doing this:

![image](https://github.com/memphis-iis/mofacts/assets/13023147/e5197b30-6de6-41df-8861-3cff28f102b7)

**Comment by imrryr** [comment]
Here is the actual example that produced the above. I was trying many configurations of the json, since I though this worked since I think it works for my experiment.... 
[TDF11.zip](https://github.com/user-attachments/files/15887085/TDF11.zip)

**Comment by imrryr** [comment]
This one also failed... 
[TDFpp.zip](https://github.com/user-attachments/files/15887115/TDFpp.zip)

**Comment by imrryr** [comment]
What it appears to be doing is making a single button for every single character in the incorrect answers

**Comment by MegaGeese** [comment]
I think I have a fix for this on staging and can make a quick pr for this

**Comment by imrryr** [comment]
No it can't be on staging this is a problem on production. I can't test all
of the other stuff that's on staging I just need this fixed.

**Comment by imrryr** [comment]
Okay but this is a problem on production and I don't want to start working
on staging for this work that's immediate. Can I talk to you on the phone?

**Comment by imrryr** [comment]
Or zoom

**Comment by MegaGeese** [comment]
Sorry if i wasnt clear, what I meant was that I have already fixed the issue on staging and can copy the fix over for production. There is currently a pull request open right now for this issue that will fix it on produciton #1498

**Comment by imrryr** [comment]
ahhh... ok, but i still would like to discuss it. I am on teams chat now if you can
