### ISSUE TITLE
Correct/Incorrect Feedback Not Displaying

### ISSUE THREAD

**Issue by Brtelfer** [memphis-iis/mofacts#1500]
Here is the zip file:
[Assessment During Learning Test.zip](https://github.com/user-attachments/files/15922676/Assessment.During.Learning.Test.zip)

Here is the link to the test: https://mofacts.optimallearning.org/experiment/testingaslearning15

The feedback messages are not showing up after answers are selected.
![image](https://github.com/memphis-iis/mofacts/assets/106611498/3a3b6a0f-e18e-431c-8430-c8c3bb611299)

Sometimes the messages will show under the answer question prompt:
![image](https://github.com/memphis-iis/mofacts/assets/106611498/d122a5c5-18ec-4f7c-9e10-10c937c6146a)

**Comment by MegaGeese** [comment]
This was fixed and is currently deployed.

**Comment by imrryr** [comment]
This was a bug in the staging code that was accidentally deployed to Mofacts server, but you did not deploy staging, so it is not deployed because the code that is deployed did not have that bug (it is from the card logic).... Please confirm @MegaGeese
