### ISSUE TITLE
Allow for admins to toggle view of other's content

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1513]
Consequently, I can't remove it, and I wonder why it is there.
![Screenshot 2024-07-05 164216](https://github.com/memphis-iis/mofacts/assets/13023147/ebc90e2e-9630-4dae-a1c4-97dc2fe09c1c)

**Comment by JRustyHaner** [comment]
@imrryr  That unit was uploaded by Blake "backslash145@gmail.com"  on  June 22. You can't remove it because it's not yours. Unless he transfers ownership or you impersonate him,  it cannot be removed.

**Comment by JRustyHaner** [comment]
@imrryr would you like admins to see and remove all TDFs? We can make that change if you'd like.

**Comment by imrryr** [comment]
@JRustyHaner the main reason why I was confused is because it's titled as one of my quizzes for my class. I can't imagine what he was doing with that. You sound pretty sure it was posted by Blake though?

**Comment by JRustyHaner** [comment]
@imrryr  I'm sure, It's in Blake's content list.

![image](https://github.com/memphis-iis/mofacts/assets/46696077/ea115cbb-8839-4eca-97f5-ec2d563605e0)

**Comment by imrryr** [comment]
Odd, yes, if it weren't to complex I think it would be great to control this. it would be great for the admin to have a toggle on the content screen to show their own content OR everyone else's (which would need to be labeled for each user). The default would be to show the admin's content.
