### ISSUE TITLE
Lockout unit does not display the lockout screen, it just locks out

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1528]
Specifically it is not showing the time remaining or the instructions (which should be on the screen below)

 "unitinstructions": "<p><strong>Congratulations on completing Part 1 of the experiment!</strong> <br /><br /> To ensure that your assignment is approved and you receive the $8 payment, please enter the code <strong>'AXDTYUY'</strong> into the Amazon Mechanical Turk website for this HIT and submit your response now. We will review your completion and approve your assignment accordingly. <br /><br /> Please note that you have a countdown of <strong>1 day</strong> for part 2 of the study. After this timeframe, you will receive a private Turk message (delivered to your email inbox normally) containing instructions for Part 2. Completing Part 2 will earn you $5, in addition to an extra bonus based on the number of correct answers you provided in Part 1. <br /><br />Thank you for your participation, and keep an eye on your email inbox for further instructions on Part 2. If you do not receive a followup email 24 hours from now, feel free to contact us. <br /><br /> After the time has passed, the continue button to go to the posttest will be activated below.</p>",
[RadicalLevels789.zip](https://github.com/user-attachments/files/16396703/RadicalLevels789.zip)

![image](https://github.com/user-attachments/assets/e7ecfdc8-65c5-452f-a451-b3ce450407bb)

**Comment by imrryr** [comment]
Perhaps this was broken when we fixed the last bug. I had been working on production in early June.

**Comment by imrryr** [comment]
It also is functionally broken and will not resume after the timeout has passed

**Comment by MegaGeese** [comment]
this bug has also been fixed in the most recent staging build. Would you like us to pull staging into main and run a deployment?

**Comment by imrryr** [comment]
Well, I'm willing to test staging where it is before we decide. I'll get back to you in about 24 hrs.

**Comment by MegaGeese** [comment]
Have you had a chance to test staging? @imrryr

**Comment by JRustyHaner** [comment]
@imrryr I'm closing this, please reopen if the issue reappears.
