### ISSUE TITLE
Issue uploading new package

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1529]
I have the final zipped package to upload for the adaptive practice study but I am getting this error message every time I try to upload it. I've tried a few things to rename it and save it in other places. I've validated all of the JSONs and they look okay there. I have the error message below and all of the files. 

No need to look at this over the weekend but it would be great if we could look at it on Monday!

<img width="586" alt="Screenshot 2024-07-26 at 8 06 14 PM" src="https://github.com/user-attachments/assets/e6c264c1-e392-4fa3-bb8b-2ae28325a16e">

[AdaptivePractice_Control TDF.json](https://github.com/user-attachments/files/16397541/AdaptivePractice_Control.TDF.json)
[Adaptive Practice_Root.json](https://github.com/user-attachments/files/16397542/Adaptive.Practice_Root.json)
[AdaptivePractice_CarbonQuestions.json](https://github.com/user-attachments/files/16397543/AdaptivePractice_CarbonQuestions.json)
[AdaptivePractice_Experiment TDF.json](https://github.com/user-attachments/files/16397544/AdaptivePractice_Experiment.TDF.json)

**Comment by JRustyHaner** [comment]
Hehe MacOS strikes again. There's hidden folders and files in Mac archives. The ._ in front of a file usually means it's a temporary file that somehow got inside your zip package.

**Comment by JRustyHaner** [comment]
@shelbik37 open the zip file and delete the __MacOSX folder. The Mac archiver utility is known for being the worst in the industry.

**Comment by shelbik37** [comment]
Thanks Rusty! I was able to delete it and uploaded successfully!
