### ISSUE TITLE
Excessive correct feedback despite uisettings

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1530]
OK,  my tdf (package attached) is producing the correct answer twice when the answer is right
"Your answer was X. Correct. The correct answer is X."  ... like that
But according to the spec, the default should be just to say "Correct"
![image](https://github.com/user-attachments/assets/a7f5cbef-dad3-4a14-8b2c-1684d4d1c686)

[unit1.zip](https://github.com/user-attachments/files/16401633/unit1.zip)

**Comment by JRustyHaner** [comment]
@imrryr this bug is not present on staging, so it might be a time for a main deploy.

**Comment by imrryr** [comment]
I created a new issue for a different problem on staging, but this issue 1530 appears fixed on staging.
