### ISSUE TITLE
Data exists, but report is blank

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1531]
![image](https://github.com/user-attachments/assets/aac46eb5-cc83-4858-8794-fdd059c11280)

**Comment by MegaGeese** [comment]
All the data for the TDF assigned to the class in the screenshot was entered while you were logged in with your imrryr@gmail.com account, and the only student in that class is your ppavlik@memphis account. The data also shows that it was a direct login and not a class login so the data would not be available for the class download. Can you confirm that this is how you logged in to log the data?

**Comment by JRustyHaner** [comment]
@imrryr I'm closing this, please reopen if the issue reappears.
