### ISSUE TITLE
Class link is flacky

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1555]
It works if everything is just so, but problems occur if there was a past login without a logout, and no available lessons show. Can we make sure that the student is logged out at the beginning of the process when the class link is clicked? Or can we detect the login and show the lessons assigned properly? 

It seems to make it work, I need to both logout AND close the browser window, then click the link to reopen. However, since it shows the login screen after the logout, it should not be necessary to close the login window to get a new one. Strangely this appears necessary.

**Comment by JRustyHaner** [comment]
@imrryr probably best to log them out whenever they visit a class link and force them to log in again
