### ISSUE TITLE
Text rendering in MC questions (only for correct answers)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1557]
Strangely, when the correct answer contains a semicolon, the correct answer button is not rendered, it is blank. The strange part is that when the semicolon is the incorrect answers it renders fine

**Comment by MegaGeese** [comment]
it seems that semicolons are used to denote branching answers. should we rewrite the branching answers criteria or just not use semicolons in answers?

**Comment by imrryr** [comment]
branching answers should not be assumed I think. That should simply be turned on with a tdf deliveryparams tag <branching>true or false
