### ISSUE TITLE
Unit 17test Prequiz appears as content despite it having been deleted previously (quite some time ago)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1560]
![Screenshot 2024-08-30 092348](https://github.com/user-attachments/assets/629f2ad6-6099-4b64-b75d-153d1c82a7b8)

**Comment by MegaGeese** [comment]
Was this deleted by you or Blake originally?

**Comment by imrryr** [comment]
I think yes that's is correct, probably me, but perhaps I gave him a test copy.

**Comment by MegaGeese** [comment]
fixed with #1565
